bi_bap/activity_statistics/urls.py
from django.conf.urls import url
from bi_bap.activity_statistics.views import *


app_name = 'activity_statistics'
urlpatterns = [
    url(r'^monthly/$', OverallMonthlyStatisticsView.as_view(), name='overall_monthly_statistics'),
    url(r'^yearly/$', OverallYearlyStatisticsView.as_view(), name='overall_yearly_statistics'),
    url(r'^all_time/$', OverallAllTimeStatisticsView.as_view(), name='overall_all_time_statistics'),

]

bi_bap/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from bi_bap import settings
from bi_bap.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^$', IndexView.as_view(), name='index'),
    # url(r'^login/$', account_view.LoginView.as_view(), name='login'),
    # url(r'^logout/$', account_view.LogoutView.as_view(), name='logout'),

    # apps
    url(r'^account/', include('bi_bap.account.urls')),
    url(r'^achievements/', include('bi_bap.achievements.urls')),
    url(r'^activities/', include('bi_bap.activities.urls')),
    url(r'^statistics/', include('bi_bap.activity_statistics.urls')),
    url(r'^rewards/', include('bi_bap.rewards.urls')),
    url(r'^home/', include('bi_bap.home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bi_bap/activity_statistics/models.py
from django.db import models

# Create your models here.

bi_bap/activity_statistics/views.py
import calendar
from datetime import date, datetime

from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
from django.views.generic import TemplateView

from bi_bap.activities.models import ActivityInstance
from bi_bap.settings import DATE_INPUT_FORMAT


class Statistics:
    completed = 0
    total = 0

    def __str__(self):
        return str(self.completed) + " " + str(self.total)

    def calculate_percentage(self):
        if self.total == 0 or self.completed == 0:
            return 0
        else:
            return round(self.completed / (self.total / 100))

    def calculate_average(self):
        if self.total == 0 or self.completed == 0:
            return 0
        else:
            return round(self.completed / self.total, 1)


def get_activity_statistics(user, date_format, activity):
    """
    Function creates data dictionaries for graphs to display statistics of an activity.
    """
    date_today = datetime.today()
    instances = list(ActivityInstance.objects.filter(activity__created_by=user, activity=activity, date__lte=date_today)
                                             .order_by("date"))

    day_dict = get_statistics_by_day(date_format, instances)
    start_activity_difficulty_dict = get_average_activity_start_difficulty(instances)
    activity_difficulty_dict = get_average_activity_difficulty(instances)
    return day_dict, start_activity_difficulty_dict, activity_difficulty_dict


def get_overall_statistics(user, date_format, start_date=None, end_date=None):
    """
    Function creates data dictionaries for graphs to display overall statistics in the chosen date interval.
    """
    date_today = datetime.today()
    if not (start_date and end_date):
        instances = list(ActivityInstance.objects.filter(activity__created_by=user,
                                                         date__lte=date_today)
                                                 .order_by("date"))

    elif date_today <= end_date:
        instances = list(ActivityInstance.objects.filter(date__gte=start_date,
                                                         date__lte=date_today,
                                                         activity__created_by=user)
                                                 .order_by("date"))
    else:
        instances = list(ActivityInstance.objects.filter(date__gte=start_date,
                                                         date__lte=end_date,
                                                         activity__created_by=user)
                                                 .order_by("date"))

    day_dict = get_statistics_by_day(date_format, instances)
    activity_dict = get_statistics_by_activities(instances)
    activity_composition_dict = get_activity_composition(instances)
    start_activity_difficulty_dict = get_average_activity_start_difficulty(instances)
    activity_difficulty_dict = get_average_activity_difficulty(instances)

    return day_dict, activity_dict, activity_composition_dict, start_activity_difficulty_dict, activity_difficulty_dict


def get_statistics_by_day(date_format, activity_instances):
    """
    Function creates data dictionary for a graph, which shows success rate of activities.
    Data on x axis are determined by date_format argument.
    Data on y axis are calculated by Statistics instances.
    """
    day_dict = {}
    for instance in activity_instances:
        instance_format = instance.date.strftime(date_format)

        if not day_dict.get(instance_format):
            day_dict[instance_format] = Statistics()

        if instance.is_complete:
            day_dict[instance_format].completed += 1

        day_dict[instance_format].total += 1

    return day_dict


def get_statistics_by_activities(activity_instances):
    """
    Function creates data dictionary for a graph, which shows the success rate of each activity.
    Data on x axis are determined by unique activities.
    Data on y axis are calculated by Statistics instances.
    """
    activity_dict = {}
    for instance in activity_instances:
        activity = instance.activity

        if not activity_dict.get(activity):
            activity_dict[activity] = Statistics()

        if instance.is_complete:
            activity_dict[activity].completed += 1

        activity_dict[activity].total += 1

    return activity_dict


def get_activity_composition(activity_instances):
    """
    Function creates data dictionary for a graph, which shows the composition of activities in the chosen date interval.
    Data on x axis are determined by unique activities.
    Data on y axis are calculated by the number of activity instances.
    """
    activity_composition_dict = {}
    for instance in activity_instances:
        activity = instance.activity

        if not activity_composition_dict.get(activity):
            activity_composition_dict[activity] = 0

        activity_composition_dict[activity] += 1

    return activity_composition_dict


def get_average_activity_start_difficulty(activity_instances):
    """
    Function creates data dictionary for a graph, which shows the average difficulty to start of each activity.
    Data on x axis are determined by unique activities.
    Data on y axis are calculated by Statistics instances.
    """
    start_activity_difficulty_dict = {}
    for instance in activity_instances:
        activity = instance.activity

        if not start_activity_difficulty_dict.get(activity):
            start_activity_difficulty_dict[activity] = Statistics()

        if instance.is_complete:
            start_activity_difficulty_dict[activity].completed += instance.start_difficulty
            start_activity_difficulty_dict[activity].total += 1

    return start_activity_difficulty_dict


def get_average_activity_difficulty(activity_instances):
    """
    Function creates data dictionary for a graph, which shows the average difficulty to complete of each activity.
    Data on x axis are determined by unique activities.
    Data on y axis are calculated by Statistics instances.
    """
    activity_difficulty_dict = {}
    for instance in activity_instances:
        activity = instance.activity

        if not activity_difficulty_dict.get(activity):
            activity_difficulty_dict[activity] = Statistics()

        if instance.is_complete:
            activity_difficulty_dict[activity].completed += instance.activity_difficulty
            activity_difficulty_dict[activity].total += 1

    return activity_difficulty_dict


class OverallMonthlyStatisticsView(LoginRequiredMixin, TemplateView):
    template_name = "overall_monthly_statistics.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date_format = DATE_INPUT_FORMAT
        if not ("date" in self.request.GET):
            date_to_show = date.today()
        else:
            try:
                date_to_show = datetime.strptime(str(self.request.GET["date"]), date_format)
            except:
                date_to_show = date.today()

        last_day = calendar.monthrange(date_to_show.year, date_to_show.month)[1]
        date_from = datetime(date_to_show.year, date_to_show.month, 1)
        date_to = datetime(date_to_show.year, date_to_show.month, last_day)
        day_dict, activity_dict, activity_composition_dict, start_activity_difficulty_dict, activity_difficulty_dict \
            = get_overall_statistics(self.request.user, date_format, date_from, date_to)

        context['date_to_show'] = date_to_show
        context['day_dict'] = day_dict
        context['activity_dict'] = activity_dict
        context['activity_composition_dict'] = activity_composition_dict
        context['start_activity_difficulty_dict'] = start_activity_difficulty_dict
        context['activity_difficulty_dict'] = activity_difficulty_dict
        return context


class OverallYearlyStatisticsView(LoginRequiredMixin, TemplateView):
    template_name = "overall_yearly_statistics.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date_format = "%m, %Y"
        if not ("date" in self.request.GET):
            date_to_show = date.today()
        else:
            try:
                date_to_show = datetime.strptime(str(self.request.GET["date"]), DATE_INPUT_FORMAT)
            except:
                date_to_show = date.today()

        date_from = datetime(date_to_show.year, 1, 1)
        date_to = datetime(date_to_show.year, 12, 31)
        day_dict, activity_dict, activity_composition_dict, start_activity_difficulty_dict, activity_difficulty_dict \
            = get_overall_statistics(self.request.user, date_format, date_from, date_to)

        context['date_to_show'] = date_to_show
        context['day_dict'] = day_dict
        context['activity_dict'] = activity_dict
        context['activity_composition_dict'] = activity_composition_dict
        context['start_activity_difficulty_dict'] = start_activity_difficulty_dict
        context['activity_difficulty_dict'] = activity_difficulty_dict
        return context


class OverallAllTimeStatisticsView(LoginRequiredMixin, TemplateView):
    template_name = "overall_all_time_statistics.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date_format = "%m, %Y"
        day_dict, activity_dict, activity_composition_dict, start_activity_difficulty_dict, activity_difficulty_dict \
            = get_overall_statistics(self.request.user, date_format)

        context['day_dict'] = day_dict
        context['activity_dict'] = activity_dict
        context['activity_composition_dict'] = activity_composition_dict
        context['start_activity_difficulty_dict'] = start_activity_difficulty_dict
        context['activity_difficulty_dict'] = activity_difficulty_dict
        return context

bi_bap/activity_statistics/templates/overall_all_time_statistics.html
{% extends 'base.html' %}
{% load static %}
{% load custom_template_tags %}

{% block include %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock %}
{% block content %}
<div class="row justify-content-end mb-2">
    <div class="d-flex justify-content-end">
        <a href="{% url 'activity_statistics:overall_yearly_statistics' %}"
           class="btn custom-btn d-flex align-items-center ms-1 shadow-none">
            Yearly
        </a>
        <a href="{% url 'activity_statistics:overall_all_time_statistics' %}"
           class="btn custom-btn d-flex align-items-center ms-1 shadow-none">
            All time
        </a>
        <a href="{% url 'activity_statistics:overall_monthly_statistics' %}"
           class="btn custom-btn d-flex align-items-center ms-1 shadow-none">
            Monthly
        </a>
    </div>
</div>
<div class="row mb-3 d-flex justify-content-center">
    <div class="align-middle text-center display-4 p-2">All time statistics</div>
</div>
<div class="row">
    {% if day_dict %}
    <div class="col-12 mb-3">
        <canvas id="day_dict_chart" width="100" height="60"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_dict_chart" width="200" height="200"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_composition_dict_chart" width="200" height="200"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_start_difficulty_dict_chart" width="200" height="200"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_difficulty_dict_chart" width="200" height="200"></canvas>
    </div>
    {% else %}
    <span class="display-4 text-center">No statistics to show</span>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
{% if day_dict %}
    <script>
    day_dict_labels = [];
    day_dict_values = [];
    {% for key, value in day_dict.items %}
        day_dict_labels.push("{{key}}");
        day_dict_values.push({{value.calculate_percentage}});
    {% endfor %}

    activity_dict_labels = [];
    activity_dict_values = [];
    {% for key, value in activity_dict.items %}
        activity_dict_labels.push("{{key}}");
        activity_dict_values.push({{value.calculate_percentage}});
    {% endfor %}

    activity_composition_dict_labels = [];
    activity_composition_dict_values = [];
    {% for key, value in activity_composition_dict.items %}
        activity_composition_dict_labels.push("{{key}}");
        activity_composition_dict_values.push({{value}});
    {% endfor %}

    start_activity_difficulty_dict_labels = [];
    start_activity_difficulty_dict_values = [];
    {% for key, value in start_activity_difficulty_dict.items %}
        start_activity_difficulty_dict_labels.push("{{key}}");
        start_activity_difficulty_dict_values.push({{value.calculate_average}});
    {% endfor %}

    activity_difficulty_dict_labels = [];
    activity_difficulty_dict_values = [];
    {% for key, value in activity_difficulty_dict.items %}
        activity_difficulty_dict_labels.push("{{key}}");
        activity_difficulty_dict_values.push({{value.calculate_average}});
    {% endfor %}
    </script>
    <script src="{% static 'js/overall_statistics.js' %}"></script>
{% endif %}
{% endblock %}

bi_bap/activity_statistics/templates/overall_monthly_statistics.html
{% extends 'base.html' %}
{% load static %}
{% load custom_template_tags %}

{% block include %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock %}
{% block content %}
<div class="row justify-content-end mb-2">
    <div class="d-flex justify-content-end">
        <a href="{% url 'activity_statistics:overall_yearly_statistics' %}"
           class="btn custom-btn d-flex align-items-center ms-1 shadow-none">
            Yearly
        </a>
        <a href="{% url 'activity_statistics:overall_all_time_statistics' %}"
           class="btn custom-btn d-flex align-items-center ms-1 shadow-none">
            All time
        </a>
        <a href="{% url 'activity_statistics:overall_monthly_statistics' %}"
           class="btn custom-btn d-flex align-items-center ms-1 shadow-none">
            Monthly
        </a>
    </div>
</div>
<div class="row mb-2 d-flex justify-content-center">
    <div class="col-md-4 col-8 d-flex flex-row justify-content-center">
        <a href="{% url 'activity_statistics:overall_monthly_statistics' %}?date={{date_to_show|get_prev_month}}" id="prev-day-button" class="btn base-square-button mr-1 shadow-none">
            <i class="fas fa-angle-left"></i>
        </a>
        <div class="align-middle text-center p-2">{{date_to_show|date:"M, Y"}}</div>
        <a href="{% url 'activity_statistics:overall_monthly_statistics' %}?date={{date_to_show|get_next_month}}" id="next-day-button" class="btn base-square-button ml-1 shadow-none">
            <i class="fas fa-angle-right"></i>
        </a>
    </div>
</div>
<div class="row">
    {% if day_dict %}
    <div class="col-12 mb-3">
        <canvas id="day_dict_chart" width="100" height="60"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_dict_chart" width="200" height="200"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_composition_dict_chart" width="200" height="200"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_start_difficulty_dict_chart" width="200" height="200"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_difficulty_dict_chart" width="200" height="200"></canvas>
    </div>
    {% else %}
    <span class="display-4 text-center">No statistics to show</span>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
{% if day_dict %}
    <script>
    day_dict_labels = [];
    day_dict_values = [];
    {% for key, value in day_dict.items %}
        day_dict_labels.push("{{key}}");
        day_dict_values.push({{value.calculate_percentage}});
    {% endfor %}

    activity_dict_labels = [];
    activity_dict_values = [];
    {% for key, value in activity_dict.items %}
        activity_dict_labels.push("{{key}}");
        activity_dict_values.push({{value.calculate_percentage}});
    {% endfor %}

    activity_composition_dict_labels = [];
    activity_composition_dict_values = [];
    {% for key, value in activity_composition_dict.items %}
        activity_composition_dict_labels.push("{{key}}");
        activity_composition_dict_values.push({{value}});
    {% endfor %}

    start_activity_difficulty_dict_labels = [];
    start_activity_difficulty_dict_values = [];
    {% for key, value in start_activity_difficulty_dict.items %}
        start_activity_difficulty_dict_labels.push("{{key}}");
        start_activity_difficulty_dict_values.push({{value.calculate_average}});
    {% endfor %}

    activity_difficulty_dict_labels = [];
    activity_difficulty_dict_values = [];
    {% for key, value in activity_difficulty_dict.items %}
        activity_difficulty_dict_labels.push("{{key}}");
        activity_difficulty_dict_values.push({{value.calculate_average}});
    {% endfor %}
    </script>
    <script src="{% static 'js/overall_statistics.js' %}"></script>
{% endif %}
{% endblock %}

bi_bap/activity_statistics/templates/overall_yearly_statistics.html
{% extends 'base.html' %}
{% load static %}
{% load custom_template_tags %}

{% block include %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock %}
{% block content %}
<div class="row justify-content-end mb-2">
    <div class="d-flex justify-content-end">
        <a href="{% url 'activity_statistics:overall_yearly_statistics' %}"
           class="btn custom-btn d-flex align-items-center ms-1 shadow-none">
            Yearly
        </a>
        <a href="{% url 'activity_statistics:overall_all_time_statistics' %}"
           class="btn custom-btn d-flex align-items-center ms-1 shadow-none">
            All time
        </a>
        <a href="{% url 'activity_statistics:overall_monthly_statistics' %}"
           class="btn custom-btn d-flex align-items-center ms-1 shadow-none">
            Monthly
        </a>
    </div>
</div>
<div class="row mb-2 d-flex justify-content-center">
    <div class="col-md-4 col-8 d-flex flex-row justify-content-center">
        <a href="{% url 'activity_statistics:overall_yearly_statistics' %}?date={{date_to_show|get_prev_year}}" id="prev-day-button" class="btn base-square-button mr-1 shadow-none">
            <i class="fas fa-angle-left"></i>
        </a>
        <div class="align-middle text-center p-2">{{date_to_show|date:"Y"}}</div>
        <a href="{% url 'activity_statistics:overall_yearly_statistics' %}?date={{date_to_show|get_next_year}}" id="next-day-button" class="btn base-square-button ml-1 shadow-none">
            <i class="fas fa-angle-right"></i>
        </a>
    </div>
</div>
<div class="row">
    {% if day_dict %}
    <div class="col-12 mb-3">
        <canvas id="day_dict_chart" width="100" height="60"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_dict_chart" width="200" height="200"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_composition_dict_chart" width="200" height="200"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_start_difficulty_dict_chart" width="200" height="200"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_difficulty_dict_chart" width="200" height="200"></canvas>
    </div>
    {% else %}
    <span class="display-4 text-center">No statistics to show</span>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
{% if day_dict %}
    <script>
    day_dict_labels = [];
    day_dict_values = [];
    {% for key, value in day_dict.items %}
        day_dict_labels.push("{{key}}");
        day_dict_values.push({{value.calculate_percentage}});
    {% endfor %}

    activity_dict_labels = [];
    activity_dict_values = [];
    {% for key, value in activity_dict.items %}
        activity_dict_labels.push("{{key}}");
        activity_dict_values.push({{value.calculate_percentage}});
    {% endfor %}

    activity_composition_dict_labels = [];
    activity_composition_dict_values = [];
    {% for key, value in activity_composition_dict.items %}
        activity_composition_dict_labels.push("{{key}}");
        activity_composition_dict_values.push({{value}});
    {% endfor %}

    start_activity_difficulty_dict_labels = [];
    start_activity_difficulty_dict_values = [];
    {% for key, value in start_activity_difficulty_dict.items %}
        start_activity_difficulty_dict_labels.push("{{key}}");
        start_activity_difficulty_dict_values.push({{value.calculate_average}});
    {% endfor %}

    activity_difficulty_dict_labels = [];
    activity_difficulty_dict_values = [];
    {% for key, value in activity_difficulty_dict.items %}
        activity_difficulty_dict_labels.push("{{key}}");
        activity_difficulty_dict_values.push({{value.calculate_average}});
    {% endfor %}
    </script>
    <script src="{% static 'js/overall_statistics.js' %}"></script>
{% endif %}
{% endblock %}