bi_bap/account/urls.py
from django.conf.urls import url
from django.urls import path

from bi_bap.account.views import *

app_name = 'account'
urlpatterns = [
    url(r'^$', AccountIndexView.as_view(), name='index_account'),
    url(r'^login/', UserLoginView.as_view(), name='login'),
    url(r'^logout/', UserLogoutView.as_view(), name='logout'),
    url(r'^register/', UserRegisterView.as_view(), name='register'),
    url(r'^password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_confirm/<slug:uidb64>/<slug:token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^notification_read/(?P<pk>[\w-]+)/$', NotificationReadView.as_view(), name='notification_read'),
    url(r'^change_password/$', PasswordChangeView.as_view(), name='change_password'),
    path('activate_registration/<slug:uidb64>/<slug:token>/', activate_registration, name='activate_registration'),
    url(r'^profile/change_email/$', EmailChangeView.as_view(), name='change_email'),
    path('activate_email/<slug:uidb64>/<slug:token>/', activate_email, name='activate_email'),
]

bi_bap/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from bi_bap import settings
from bi_bap.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^$', IndexView.as_view(), name='index'),
    # url(r'^login/$', account_view.LoginView.as_view(), name='login'),
    # url(r'^logout/$', account_view.LogoutView.as_view(), name='logout'),

    # apps
    url(r'^account/', include('bi_bap.account.urls')),
    url(r'^achievements/', include('bi_bap.achievements.urls')),
    url(r'^activities/', include('bi_bap.activities.urls')),
    url(r'^statistics/', include('bi_bap.activity_statistics.urls')),
    url(r'^rewards/', include('bi_bap.rewards.urls')),
    url(r'^home/', include('bi_bap.home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bi_bap/account/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm, \
    SetPasswordForm
from django.core.exceptions import ValidationError
from django.forms import EmailField, ModelForm

from bi_bap.account.models import User


class UserLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'Enter username'
        self.fields['password'].widget.attrs['placeholder'] = 'Enter password'

        self.fields['username'].widget.attrs['class'] = 'form-control shadow-none'
        self.fields['password'].widget.attrs['class'] = 'form-control shadow-none'

        self.fields['username'].widget.attrs['autocomplete'] = 'off'
        self.fields['password'].widget.attrs['autocomplete'] = 'off'


class UserRegisterForm(UserCreationForm):
    email = EmailField()

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'Enter username'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Enter password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Enter password again'

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control shadow-none'

        self.fields['username'].widget.attrs['autocomplete'] = 'off'
        self.fields['password1'].widget.attrs['autocomplete'] = 'off'
        self.fields['password2'].widget.attrs['autocomplete'] = 'off'

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ChangePasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        for field_name in ('old_password', 'new_password1', 'new_password2'):
            # remove helper text
            self.fields[field_name].help_text = None
            # remove labels
            self.fields[field_name].label = False

            self.fields[field_name].widget.attrs['class'] = 'form-control shadow-none'

        self.fields['old_password'].widget.attrs['placeholder'] = "Current password"
        self.fields['new_password1'].widget.attrs['placeholder'] = "New password"
        self.fields['new_password2'].widget.attrs['placeholder'] = "New password confirmation"

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']


class UserChangeEmailForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['temp_email'].widget.attrs['placeholder'] = "New email"
        self.fields['temp_email'].label = False
        self.fields['temp_email'].widget.attrs['class'] = 'form-control shadow-none'

    def clean_temp_email(self):
        temp_email = self.cleaned_data.get('temp_email')

        # Check to see if any users already exist with this email as a username.
        try:
            match = User.objects.get(email=temp_email)
        except User.DoesNotExist:
            # Unable to find a user, this is fine
            return temp_email

        # A user was found with this as a username, raise an error.
        raise ValidationError("This email has already been registered.")

    class Meta:
        model = User
        fields = ['temp_email']


class ChangeProfilePicture(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['profile_pic'].widget.attrs['class'] = 'form-control shadow-none'

    class Meta:
        model = User
        fields = ['profile_pic']


class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)

        self.fields['email'].widget.attrs['placeholder'] = 'Enter email address'

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control shadow-none'

        self.fields['email'].widget.attrs['autocomplete'] = 'off'


class UserSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(UserSetPasswordForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control shadow-none'

bi_bap/account/views.py
from datetime import date

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404

# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import FormView
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView as AuthPasswordChangeView, \
    PasswordResetView, PasswordResetConfirmView

from bi_bap.account.forms import UserLoginForm, UserRegisterForm, ChangePasswordForm, UserChangeEmailForm, \
    ChangeProfilePicture, UserPasswordResetForm, UserSetPasswordForm
from bi_bap.account.models import User, Notification
from bi_bap.account.tokens import account_token_generator
from bi_bap.achievements.models import Achievement
from bi_bap.activities.models import ActivityInstance
from bi_bap.settings import EMAIL_HOST_USER, SEND_EMAILS


class AccountIndexView(LoginRequiredMixin, FormView):
    template_name = "index_account.html"
    form_class = ChangeProfilePicture
    success_url = reverse_lazy("account:index_account")

    def form_valid(self, form):
        form = self.form_class(self.request.POST, self.request.FILES, instance=self.request.user)
        form.save()
        self.request.user.profile_pic = form.cleaned_data['profile_pic']
        self.request.user.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # calculate completed achievements
        recent_achievements = Achievement.objects.filter(created_by=self.request.user)
        achievements_total = 0
        achievements_complete = 0
        recent_completed_achievements = []
        for achievement in recent_achievements:
            if achievement.is_complete:
                achievements_complete += 1
                recent_completed_achievements.append(achievement)
            achievements_total += 1

        # calculate completed activities for today
        instances = ActivityInstance.objects.filter(activity__created_by=self.request.user, date=date.today())
        instances_total = 0
        instances_complete = 0
        for instance in instances:
            if instance.is_complete:
                instances_complete += 1
            instances_total += 1

        context['achievements_total'] = achievements_total
        context['achievements_complete'] = achievements_complete
        context['instances_total'] = instances_total
        context['instances_complete'] = instances_complete
        context['recent_completed_achievements'] = recent_completed_achievements[:5]
        return context


class UserRegisterView(FormView):
    """
    View displays email change form and sends verification link to the entered email.
    """
    form_class = UserRegisterForm
    template_name = "register.html"
    success_url = reverse_lazy("account:register")

    def form_valid(self, form):
        try:
            with transaction.atomic():
                form = self.form_class(self.request.POST)
                user = form.save()
                current_site = get_current_site(self.request)
                subject = 'Confirm your email address'
                user.is_active = False
                user.signup_confirmation = False
                user.save()
                # load a template like get_template()
                # and calls its render() method immediately.
                message = render_to_string('activation_request_register.html', {
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    # method will generate a hash value with user related data
                    'token': account_token_generator.make_token(user),
                })
                messages.success(self.request, "Email has been sent. Check your email for further details.")

                if SEND_EMAILS:
                    user.email_user(subject, message, fail_silently=False)
                else:
                    print(message)

                return super().form_valid(form)

        except Exception as e:
            messages.warning(self.request,
                             "Error trying to send email. If problem persists, please contact staff members.")
            return super().form_invalid(form)


def activate_registration(request, uidb64, token):
    """
    Function checks the token sent during the registration process,
    if the token is valid then the email is verified and the registration process is finished,
    otherwise an error message is shown.
    """
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    # checking if the user exists and if the token is valid.
    if user is not None and account_token_generator.check_token(user, token):
        user.is_active = True
        user.signup_confirmation = True
        user.save()
        login(request, user)
        messages.success(request, "Welcome " + user.username + "!")
        return redirect('account:index_account')
    else:
        messages.warning(request,
                         "Link has expired.")
        return redirect('account:register')


class PasswordChangeView(LoginRequiredMixin, AuthPasswordChangeView):
    """
    View displays a form to change password
    """
    form_class = ChangePasswordForm
    success_url = reverse_lazy("account:index_account")
    template_name = "password_change.html"


class EmailChangeView(LoginRequiredMixin, FormView):
    """
    View displays email change form and sends an verification link to the entered email,
    newly entered email is saved in a temporary variable.
    """
    template_name = 'email_change.html'
    form_class = UserChangeEmailForm
    success_url = reverse_lazy('account:index_account')

    def form_valid(self, form):
        try:
            with transaction.atomic():
                form = self.form_class(self.request.POST, instance=self.request.user)
                form.save()
                self.request.user.temp_email = form.cleaned_data['temp_email']
                self.request.user.save()
                current_site = get_current_site(self.request)
                subject = 'Confirm your new email.'
                # load a template like get_template()
                # and calls its render() method immediately.
                message = render_to_string('activation_request_email.html', {
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(self.request.user.pk)),
                    # method will generate a hash value with user related data
                    'token': account_token_generator.make_token(self.request.user),
                })

                if SEND_EMAILS:
                    send_mail(subject, message, EMAIL_HOST_USER, [str(self.request.user.temp_email)],
                              fail_silently=False)
                else:
                    print(message)

                messages.success(self.request, "Email has been sent. Check your new email for further details.")
                return super().form_valid(form)

        except Exception as e:
            messages.warning(self.request, "Error trying to send email. If problem persists, please contact staff members.")
            return super().form_invalid(form)


def activate_email(request, uidb64, token):
    """
    Function checks token sent during email change process,
    if the token is valid then the new email address is verified and the new email
    is set as the current email, otherwise an error message is shown.
    """
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    # checking if the user exists, if the token is valid.
    if user is not None and account_token_generator.check_token(user, token):

        user.email = user.temp_email
        user.temp_email = None
        user.save()
        login(request, user)
        messages.success(request, "Email has been changed.")
        return redirect('home:home_weekly')
    else:
        messages.warning(request,
                         "Link has expired.")
        return redirect('account:change_email')


class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = "login.html"
    success_url = reverse_lazy("account:index_account")


class UserLogoutView(LogoutView):
    pass


class UserPasswordResetView(PasswordResetView):
    template_name = "password_reset.html"
    email_template_name = "password_reset_email.html"
    success_url = reverse_lazy("account:password_reset")
    form_class = UserPasswordResetForm

    def form_valid(self, form):
        messages.success(self.request, "Email has been sent. Check your email for further details.")
        return super().form_valid(form)


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "password_reset_confirm.html"
    post_reset_login = True
    success_url = reverse_lazy("account:index_account")
    form_class = UserSetPasswordForm

    def form_valid(self, form):
        messages.success(self.request, "Password has been successfully reset.")
        return super().form_valid(form)


class NotificationReadView(LoginRequiredMixin, View):

bi_bap/account/templates/activation_request_email.html
{% autoescape off %}
Please confirm your new email address.

Click on this link to verify your new email address:

http://{{ domain }}{% url 'account:activate_email' uidb64=uid token=token %}

{% endautoescape %}

bi_bap/account/templates/activation_request_register.html
{% autoescape off %}
Please confirm your new email address to complete the registration process.

Click on this link to verify your email address:

http://{{ domain }}{% url 'account:activate_registration' uidb64=uid token=token %}
{% endautoescape %}

bi_bap/account/templates/email_change.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="pe-3 ps-3">
        <h1 class="display-4 p-2">Change email</h1>
        <ul class="list-group list-group-flush">
            {% if form.errors %}
            <li class="list-group-item background-lightest">
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            </li>
            {% endif %}
            <li class="list-group-item background-lightest">
                <div class="row">
                    <div class="form-group col-12 mt-2 mb-3">
                        {{form.temp_email}}
                    </div>
                </div>
            </li>
        </ul>
        <button type="submit" class="ms-3 btn custom-btn">Submit</button>
    </div>
</form>

{% endblock %}

bi_bap/account/templates/index_account.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row d-flex mb-3"><span class="display-4 text-center text-color-darkest">Profile</span></div>
<div class="row mb-4">
    <div class="col-md-6 col-12 h-100 ps-2 d-flex flex-column align-items-center">
        <span class="w-75 text-center h5">Level {{user.level}}</span>
        <div class="progress w-75 mb-2">
            <div class="progress-bar progress-bar-striped progress-bar-animated bg-success" role="progressbar"
                 style="width: {{user.calculate_progress}}%"
                 aria-valuenow="{{user.level_progress}}" aria-valuemin="0" aria-valuemax="{{user.level_goal}}">
                {{user.level_progress}}/{{user.level_goal}}
            </div>
        </div>

        <img src="{{user.profile_pic.url}}" class="profile-image w-75 rounded mb-1" alt="Profile picture">
        <form enctype="multipart/form-data" method="POST" action=""
              class="col-12 d-flex justify-content-center align-items-center w-75 px-1 my-1">
            {% csrf_token %}
            <div class="w-75">
                {{form.profile_pic}}
            </div>
            <button name="file_upload" type="submit" class="custom-btn btn w-25">
                <i class="fas fa-cloud-upload-alt"></i>
            </button>
        </form>
        <div class="col-12 px-1 text-center my-1">
            <a class="btn custom-btn w-75" href="{% url 'account:change_password' %}">Change Password</a>
        </div>
        <div class="col-12 px-1 text-center my-1">
            <a class="btn custom-btn w-75" href="{% url 'account:change_email' %}">Change Email</a>
        </div>
    </div>
    <div class="col-md-6 col-12 h-100 ps-2 d-flex flex-column align-items-center">
        <div class="row w-100 my-lg-4 my-2">
            <div class="col-6 d-flex flex-column align-items-center">
                <span class="h6 text-color-darkest">Achievements</span>
                <i class="fas fa-trophy mb-1 text-color-darkest" style="font-size: 2.5rem;"></i>
                <span class="h5">{{achievements_complete}}/{{achievements_total}}</span>
            </div>
            <div class="col-6 d-flex flex-column align-items-center">
                <span class="h6 text-color-darkest">Today's activities</span>
                <i class="fas fa-calendar-alt mb-1 text-color-darkest" style="font-size: 2.5rem;"></i>
                <span class="h5">{{instances_complete}}/{{instances_total}}</span>
            </div>
        </div>
        <div class="col-md-12 ms-md-2 ms-5 col-11 p-1">
            <span class="h2">Recent achievements:</span>
            {% for achievement in recent_completed_achievements %}
            <div class="row my-2">
                <div class="col-md-2 col-2 pe-0 d-flex flex-column justify-content-center">
                    <img src="{% static 'img/' %}{{achievement.picture}}" class="w-75">
                </div>
                <div class="col-md-10 col-10 d-flex flex-column justify-content-center">
                    <span class="align-middle h6 mb-1">{{achievement.activity}}</span>
                    <span>{{achievement}}</span>
                </div>
            </div>
            {% empty %}
            <span class="h6"></span>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

bi_bap/account/templates/login.html
{% extends 'index.html' %}
{% load static %}
{% block include %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
        <div class="container gradient-bg d-flex align-items-center justify-content-center h-100">
            <div class="row w-100 text-white mt-4">
                <div class="col-lg-6 col-md-10 col-sm-12 col-12 mx-auto text-center">
                    <div class="shadow-lg form p-4 background-lightest rounded border border-dark">
                        <h1 class="title display-4 py-2 text-truncate text-dark">WELCOME</h1>

                        <div class="form-wrapper px-2 mt-4">
                            <form method="POST" class="justify-content-center">
                                {% csrf_token %}
                                <div class="form-group mb-3 mx-5">
                                    <label class="text-dark h6">Username</label>
                                    <div class="input-group">
                                        {{ form.username }}
                                    </div>
                                </div>

                                <div class="form-group mb-3 mx-5">
                                    <label class="text-dark h6">Password</label>
                                    <div class="input-group">
                                        {{ form.password }}
                                    </div>
                                </div>
                                <div class="form-group mx-5">
                                    <label class="text-dark h6">Need an account? Register <a href="{% url 'account:register' %}">here</a> </label>
                                </div>
                                <div class="form-group mb-3 mx-5">
                                    <label class="text-dark h6"><a href="{% url 'account:password_reset' %}">Forgotten password</a></label>
                                </div>


                                {% if form.errors %}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <p class="text-danger font-weight-bold">{{ error|escape }}</p>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                            <p class="text-danger font-weight-bold">{{ error|escape }}</p>
                                    {% endfor %}
                                {% endif %}

                                <button type="submit" class="btn custom-btn"><i class="fas fa-sign-in-alt"></i> Log in</button>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
{% endblock %}

bi_bap/account/templates/password_change.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="pe-3 ps-3">
        <h1 class="display-4 p-2">Change password</h1>
        <ul class="list-group list-group-flush">
            {% if form.errors %}
            <li class="list-group-item background-lightest">
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            </li>
            {% endif %}
            <li class="list-group-item background-lightest">
                <div class="row">
                    <div class="form-group col-12 mt-2 mb-3">
                        {{form.old_password}}
                    </div>
                    <div class="form-group col-12 mb-3">
                        {{form.new_password1}}
                    </div>
                    <div class="form-group col-12 mb-3">
                        {{form.new_password2}}
                    </div>
                </div>
            </li>
        </ul>
        <button type="submit" class="ms-3 btn custom-btn">Submit</button>
    </div>
</form>

{% endblock %}

bi_bap/account/templates/password_reset_email.html
{% autoescape off %}
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'account:password_reset_confirm' uidb64=uid token=token %}
{% endautoescape %}

bi_bap/account/templates/register.html
{% extends 'index.html' %}
{% load static %}
{% block include %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
    <div class="h-100 text-dark">
        <div>
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} text-center align-center w-100 h6" id="hideMe" >{{ message }}</div>
            {% endfor %}
        </div>
        <div class="container d-flex align-items-center justify-content-center h-100">
            <div class="row w-100 text-white mt-4">
                <div class="col-lg-6 col-md-10 col-sm-12 col-12 mx-auto text-center">
                    <div class="shadow-lg form p-4 background-lightest rounded border border-dark">
                        <h1 class="title display-4 py-2 text-truncate text-dark">REGISTER</h1>

                        <div class="form-wrapper px-2 mt-4">
                            <form method="POST" class="justify-content-center">
                                {% csrf_token %}
                                <div class="form-group mb-3 mx-5">
                                    <label class="text-dark h6">Username</label>
                                    <div class="input-group">
                                        {{ form.username }}
                                    </div>
                                </div>
                                <div class="form-group mb-3 mx-5">
                                    <label class="text-dark h6">Email</label>
                                    <div class="input-group">
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-group mb-3 mx-5">
                                    <label class="text-dark h6">Password</label>
                                    <div class="input-group">
                                        {{ form.password1 }}
                                    </div>
                                </div>
                                <div class="form-group mb-4 mx-5">
                                    <label class="text-dark h6">Password</label>
                                    <div class="input-group">
                                        {{ form.password2 }}
                                    </div>
                                </div>
                                <div class="form-group mx-5 mb-3">
                                    <label class="text-dark h6">Already have an account? Login <a href="{% url 'account:login' %}">here</a> </label>
                                </div>
                                {% if form.errors %}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <p class="text-danger font-weight-bold">{{ error|escape }}</p>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                            <p class="text-danger font-weight-bold">{{ error|escape }}</p>
                                    {% endfor %}
                                {% endif %}
                                <button type="submit" class="btn w-25 custom-btn">Submit</button>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
</div>
{% endblock %}