bi_bap/achievements/urls.py
from django.conf.urls import url

from bi_bap.achievements.views import *

app_name = 'achievements'
urlpatterns = [
    url(r'^$', AchievementDetailView.as_view(), name='index_achievements'),
    url(r'^(?P<pk>[\w-]+)/$', AchievementDetailView.as_view(), name='achievement_detail'),

]

bi_bap/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from bi_bap import settings
from bi_bap.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^$', IndexView.as_view(), name='index'),
    # url(r'^login/$', account_view.LoginView.as_view(), name='login'),
    # url(r'^logout/$', account_view.LogoutView.as_view(), name='logout'),

    # apps
    url(r'^account/', include('bi_bap.account.urls')),
    url(r'^achievements/', include('bi_bap.achievements.urls')),
    url(r'^activities/', include('bi_bap.activities.urls')),
    url(r'^statistics/', include('bi_bap.activity_statistics.urls')),
    url(r'^rewards/', include('bi_bap.rewards.urls')),
    url(r'^home/', include('bi_bap.home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bi_bap/achievements/models.py
from django.db import models

# Create your models here.
from bi_bap.account.models import User, Notification
from bi_bap.activities.models import Activity
from bi_bap.settings import IMG_DIR

NUMBER_OF_COMPLETION = 0
HOT_STREAK = 1

ACHIEVEMENT_TYPES = (
    (NUMBER_OF_COMPLETION, "Number of Completion"),
    (HOT_STREAK, "Hot Streak"),
)


class Achievement(models.Model):
    activity = models.ForeignKey(Activity, verbose_name="Activity", on_delete=models.CASCADE, related_name="achievements")
    type = models.IntegerField(default=0, choices=ACHIEVEMENT_TYPES)
    created_by = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE, related_name="achievements")
    progress = models.IntegerField(verbose_name="Progress", default=0)
    goal = models.IntegerField(verbose_name="Goal", default=0)
    is_complete = models.BooleanField("Complete", default=False)
    picture = models.FilePathField(path=IMG_DIR, default="completion.png")

    def calculate_progress(self):
        if self.progress == 0 or self.goal == 0:
            return 0
        else:
            return round(self.progress / (self.goal / 100))

    def evaluate_completion_achievement(self, activity_instance):
        if activity_instance.is_complete:
            self.progress = self.progress + 1
        else:
            self.progress = self.progress - 1

        if self.goal == self.progress:
            self.is_complete = True
            self.create_notification()
        self.save()

    def evaluate_streak_achievement(self):
        activity_instances = self.activity.activity_instances.all().order_by('date')
        streak = 0
        best_streak = 0
        for activity_instance in activity_instances:
            if activity_instance.is_complete:
                streak = streak + 1
                if streak > best_streak:
                    best_streak = streak
                if streak == self.goal:
                    self.is_complete = True
                    self.create_notification()
                    break
            else:
                streak = 0
        self.progress = best_streak
        self.save()

    def evaluate_achievement(self, activity_instance):
        if self.is_complete:
            return

        if self.type == NUMBER_OF_COMPLETION:
            return self.evaluate_completion_achievement(activity_instance)
        elif self.type == HOT_STREAK:
            return self.evaluate_streak_achievement()

    def create_notification(self):
        if self.type == NUMBER_OF_COMPLETION:
            Notification.objects.create(text=f"Completed {self.activity.name} {self.goal} times.", created_by=self.created_by)
        elif self.type == HOT_STREAK:
            Notification.objects.create(text=f"Completed {self.activity.name} {self.goal} times in a row.", created_by=self.created_by)
        else:
            return

    def __str__(self):
        if self.type == NUMBER_OF_COMPLETION:
            return f"Complete habit {self.goal} times"
        elif self.type == HOT_STREAK:
            return f"Complete habit {self.goal} times in a row"
        else:
            return ""

bi_bap/achievements/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic import TemplateView, UpdateView

from bi_bap.achievements.models import Achievement, NUMBER_OF_COMPLETION, HOT_STREAK
from bi_bap.activities.models import Activity


def create_num_of_completion_achievement(new_activity, user, num_of_equal_parts, total_instances):
    """
    Function creates new completion achievements.
    The goal of each achievement is increments of total number of instances divided by num_of_equal_parts.
    """
    new_achievements = []
    for i in range(1, num_of_equal_parts + 1):
        goal = round((total_instances/num_of_equal_parts)*i)
        new_achievements.append(
            Achievement(activity=new_activity, created_by=user, type=NUMBER_OF_COMPLETION, progress=0, goal=goal, picture="completion.png"))

    return new_achievements


def create_streak_achievement(new_activity, user, completion_percentage, total_instances):
    """
    Function creates new streak achievements.
    Completion percentage sets the max number of instances to be counted as a streak.
    The goal of each streak achievement is calculated by increments of 7.
    """
    new_achievements = []
    stop = round((total_instances/100)*completion_percentage)
    for i in range(7, stop, 7):
        new_achievements.append(
            Achievement(activity=new_activity, created_by=user, type=HOT_STREAK, progress=0, goal=i, picture="streak.png"))

    return new_achievements


class AchievementDetailView(LoginRequiredMixin, TemplateView):
    template_name = "achievement_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            kwargs_pk = self.kwargs['pk']
            current_activity = get_object_or_404(Activity, pk=kwargs_pk, created_by=self.request.user)
            achievements = Achievement.objects.filter(activity=current_activity, created_by=self.request.user).order_by('is_complete')
        except KeyError:
            achievements = Achievement.objects.filter(created_by=self.request.user).order_by('is_complete')
            current_activity = None

        activities = Activity.objects.filter(created_by=self.request.user)
        context['current_activity'] = current_activity
        context['achievements'] = achievements
        context['activities'] = activities
        return context

bi_bap/achievements/templates/achievement_detail.html
{% extends 'base.html' %}
{% load static %}
{% block include %}
<link rel="stylesheet" href="{% static 'css/achievements/achievements.css' %}">
{% endblock %}

{% block content %}
<div class="row mb-3 mt-3"><span class="display-4 d-flex justify-content-center text-color-darkest">Achievements</span></div>
<div class="achievement-container box-shadow row d-flex flex-column align-items-center mx-1">
    <div id="activity-scrollbar" class="activity-list justify-content-center">
        {% if not current_activity %}
        <div class="activity-list-item">
            <a class="align-middle current-link" href="{% url 'achievements:index_achievements' %}">View all</a>
        </div>
        {% else %}
        <div class="activity-list-item">
            <a class="align-middle custom-link" href="{% url 'achievements:index_achievements' %}">View all</a>
        </div>
        {% endif %}
        {% for activity in activities %}
        {% if current_activity == activity %}
        <div class="activity-list-item">
            <a class="align-middle current-link" href="{% url 'achievements:achievement_detail' pk=activity.pk %}">{{activity}}</a>
        </div>
        {% else %}
        <div class="activity-list-item">
            <a class="align-middle custom-link" href="{% url 'achievements:achievement_detail' pk=activity.pk %}">{{activity}}</a>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="achievement-list d-flex flex-row row">
        {% for achievement in achievements %}
        <div class="achievement-list-item col-lg-4 col-sm-6 col-12 p-2">
            <div class="card h-100">
                <div class="p-3 d-flex justify-content-center">
                    <img src="{% static 'img/' %}{{achievement.picture}}" class="w-75">
                </div>
                    <div class="progress">
                      <div class="progress-bar bg-success" role="progressbar" style="width: {{achievement.calculate_progress}}%" aria-valuenow="{{achievement.progress}}" aria-valuemin="0" aria-valuemax="{{achievement.goal}}">
                          {{achievement.progress}}/{{achievement.goal}}
                      </div>
                    </div>
                <div class="card-body">
                    <h5 class="card-title">{{achievement.activity}}</h5>
                    <p class="card-text">{{achievement}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row">
            <span>No achievements found.</span>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}