bi_bap/activities/urls.py
from django.conf.urls import url

from bi_bap.activities.views import *

app_name = 'activities'
urlpatterns = [
    url(r'^$', ActivitiesIndexView.as_view(), name='index_activities'),
    url(r'^create_activity/$', CreateActivityView.as_view(), name='create_activity'),
    url(r'^delete_activity/(?P<pk>[\w-]+)/$', DeleteActivityView.as_view(), name='delete_activity'),
    url(r'^update_activity/(?P<pk>[\w-]+)/$', UpdateActivityView.as_view(), name='update_activity'),
    url(r'^activity_statistics/(?P<pk>[\w-]+)/$', ActivityStatisticsView.as_view(), name='activity_statistics'),
    url(r'^update_activity_instance/(?P<pk>[\w-]+)/$', UpdateActivityInstanceView.as_view(), name='update_activity_instance'),

]

bi_bap/activity_statistics/urls.py
from django.conf.urls import url
from bi_bap.activity_statistics.views import *


app_name = 'activity_statistics'
urlpatterns = [
    url(r'^monthly/$', OverallMonthlyStatisticsView.as_view(), name='overall_monthly_statistics'),
    url(r'^yearly/$', OverallYearlyStatisticsView.as_view(), name='overall_yearly_statistics'),
    url(r'^all_time/$', OverallAllTimeStatisticsView.as_view(), name='overall_all_time_statistics'),

]

bi_bap/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from bi_bap import settings
from bi_bap.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^$', IndexView.as_view(), name='index'),
    # url(r'^login/$', account_view.LoginView.as_view(), name='login'),
    # url(r'^logout/$', account_view.LogoutView.as_view(), name='logout'),

    # apps
    url(r'^account/', include('bi_bap.account.urls')),
    url(r'^achievements/', include('bi_bap.achievements.urls')),
    url(r'^activities/', include('bi_bap.activities.urls')),
    url(r'^statistics/', include('bi_bap.activity_statistics.urls')),
    url(r'^rewards/', include('bi_bap.rewards.urls')),
    url(r'^home/', include('bi_bap.home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bi_bap/activities/models.py
from django.db import models

# Create your models here.
from bi_bap.account.models import User

SCALE = (
    (1, "Very easy"),
    (2, "Easy"),
    (3, "Neutral"),
    (4, "Hard"),
    (5, "Very hard"),
)

class Activity(models.Model):
    name = models.CharField("Name", max_length=20)
    created_by = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE, related_name="activities")
    start_date = models.DateField("Start date")
    end_date = models.DateField("End date")
    monday = models.BooleanField(default=False, blank=True)
    tuesday = models.BooleanField(default=False, blank=True)
    wednesday = models.BooleanField(default=False, blank=True)
    thursday = models.BooleanField(default=False, blank=True)
    friday = models.BooleanField(default=False, blank=True)
    saturday = models.BooleanField(default=False, blank=True)
    sunday = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return str(self.name)

    def get_interval(self):
        return self.start_date.strftime("%d/%m/%Y") + " - " + self.end_date.strftime("%d/%m/%Y")


class ActivityInstance(models.Model):
    activity = models.ForeignKey(Activity, verbose_name="Activity", on_delete=models.CASCADE, related_name="activity_instances")
    is_complete = models.BooleanField("Complete", default=False)
    start_difficulty = models.IntegerField(default=1, choices=SCALE)
    activity_difficulty = models.IntegerField(default=1, choices=SCALE)
    date = models.DateField("Date")

    def __str__(self):
        return str(self.activity.name) + ": " + str(self.date)

bi_bap/activity_statistics/models.py
from django.db import models

# Create your models here.

bi_bap/activities/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField, ChoiceField, RadioSelect
from bootstrap_datepicker_plus.widgets import DatePickerInput
from bi_bap.activities.models import Activity
from bi_bap.settings import DATE_INPUT_FORMAT

activity_edit_choices = [('extend', 'Extend'),
                         ('shorten', 'Shorten'),
                         ('generate again', 'Generate again')]


class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        fields = ['name', 'start_date', 'end_date', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday',
                  'sunday']
        widgets = {
            'start_date': DatePickerInput(format=DATE_INPUT_FORMAT),
            'end_date': DatePickerInput(format=DATE_INPUT_FORMAT),
        }

    def __init__(self, *args, **kwargs):
        super(ActivityForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            if field in ['name', 'start_date', 'end_date']:
                self.fields[field].widget.attrs['class'] = 'form-control shadow-none'
            else:
                self.fields[field].widget.attrs['class'] = 'form-check-input'

    def clean(self):
        cleaned_data = super(ActivityForm, self).clean()

        if "start_date" not in cleaned_data or "end_date" not in cleaned_data:
            raise ValidationError("Invalid date format.")

        if cleaned_data['start_date'] >= cleaned_data['end_date']:
            raise ValidationError("Invalid date range.")

        if not cleaned_data['monday'] and not cleaned_data['tuesday'] and not cleaned_data['wednesday'] \
                and not cleaned_data['thursday'] and not cleaned_data['friday'] \
                and not cleaned_data['saturday'] and not cleaned_data['sunday']:
            raise ValidationError("Choose at least one weekday.")
        return cleaned_data


class ActivityEditForm(ActivityForm):
    action = ChoiceField(choices=activity_edit_choices)
    old_instance_start_date = None
    old_instance_end_date = None

    def __init__(self, *args, **kwargs):
        super(ActivityEditForm, self).__init__(*args, **kwargs)
        self.old_instance_start_date = self.instance.start_date
        self.old_instance_end_date = self.instance.end_date
        self.fields['action'].widget.attrs['class'] = 'form-select'

    def clean(self):
        cleaned_data = super(ActivityEditForm, self).clean()

        if self.instance.start_date and cleaned_data['action'] == 'extend' and cleaned_data['start_date'] > self.instance.start_date:
            raise ValidationError("Start date cannot be higher than previous start date.")

        if self.instance.end_date and cleaned_data['action'] == 'extend' and cleaned_data['end_date'] < self.instance.end_date:
            raise ValidationError("End date cannot be lower than previous end date.")

        if self.instance.start_date and cleaned_data['action'] == 'shorten' and cleaned_data['start_date'] < self.instance.start_date:
            raise ValidationError("Start date cannot be lower than previous start date.")

        if self.instance.end_date and cleaned_data['action'] == 'shorten' and cleaned_data['end_date'] > self.instance.end_date:
            raise ValidationError("End date cannot be higher previous end date.")

bi_bap/activities/views.py
from datetime import timedelta, datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView
from django.views.generic.base import View

from bi_bap.achievements.models import Achievement
from bi_bap.achievements.views import create_num_of_completion_achievement, create_streak_achievement
from bi_bap.activities.forms import ActivityForm, ActivityEditForm
from bi_bap.activities.models import Activity, ActivityInstance
from bi_bap.activity_statistics.views import get_activity_statistics


class ActivitiesIndexView(LoginRequiredMixin, TemplateView):
    template_name = "index_activities.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_activities"] = Activity.objects.filter(created_by=self.request.user).order_by("name")
        return context


def generate_activity_by_weekday(start_date, end_date, activity, target_weekday):
    """
    Generates activity instances for a weekday in a given date interval.
    """
    date_offset = target_weekday - start_date.isoweekday()
    if date_offset < 0:
        date = start_date + timedelta(7 + date_offset)
    else:
        date = start_date + timedelta(date_offset)
    activities = []
    while date <= end_date:
        activities.append(ActivityInstance(activity=activity, date=date))
        date = date + timedelta(7)

    return activities


def generate_activity(start_date, end_date, activity, *days):
    new_activities = []
    if len(days) != 7:
        return new_activities

    target_weekday = 1
    for day in days:
        if day is True:
            new_activities += generate_activity_by_weekday(start_date, end_date, activity, target_weekday)
        target_weekday += 1

    return new_activities


class CreateActivityView(LoginRequiredMixin, CreateView):
    form_class = ActivityForm
    template_name = "create_activity.html"
    success_url = reverse_lazy('activities:index_activities')

    def form_valid(self, form):
        new_activity = form.save(commit=False)
        new_activity.created_by = self.request.user
        cleaned_data = form.cleaned_data
        start_date = cleaned_data['start_date']
        end_date = cleaned_data['end_date']

        new_activities = generate_activity(start_date, end_date, new_activity,
                                           cleaned_data['monday'], cleaned_data['tuesday'], cleaned_data['wednesday'],
                                           cleaned_data['thursday'], cleaned_data['friday'], cleaned_data['saturday'],
                                           cleaned_data['sunday'])

        new_activity.save()

        if new_activities:
            new_achievements = []
            total_activities = len(new_activities)
            new_achievements += create_num_of_completion_achievement(new_activity, self.request.user, 4, total_activities)
            new_achievements += create_streak_achievement(new_activity, self.request.user, 50, total_activities)
            ActivityInstance.objects.bulk_create(new_activities)
            Achievement.objects.bulk_create(new_achievements)

        return super(CreateActivityView, self).form_valid(form)


class UpdateActivityView(LoginRequiredMixin, UpdateView):
    model = Activity
    form_class = ActivityEditForm
    template_name = "update_activity.html"
    success_url = reverse_lazy('activities:index_activities')

    def form_valid(self, form):
        cleaned_data = form.cleaned_data
        start_date = cleaned_data['start_date']
        end_date = cleaned_data['end_date']
        activities_to_create = []
        new_activities = generate_activity(start_date, end_date, form.instance,
                                           cleaned_data['monday'],
                                           cleaned_data['tuesday'],
                                           cleaned_data['wednesday'],
                                           cleaned_data['thursday'],
                                           cleaned_data['friday'],
                                           cleaned_data['saturday'],
                                           cleaned_data['sunday'])

        if cleaned_data['action'] == 'extend':
            for new_activity in new_activities:
                if new_activity.date < form.old_instance_start_date or new_activity.date > form.old_instance_end_date:
                    activities_to_create.append(new_activity)

        elif cleaned_data['action'] == 'shorten':
            ActivityInstance.objects.filter(activity=form.instance).exclude(date__gte=start_date, date__lte=end_date).delete()
        else:
            ActivityInstance.objects.filter(activity=form.instance).delete()
            activities_to_create = new_activities

        if activities_to_create:
            ActivityInstance.objects.bulk_create(activities_to_create)

        return super(UpdateActivityView, self).form_valid(form)


class DeleteActivityView(LoginRequiredMixin, DeleteView):
    model = Activity
    success_url = reverse_lazy('activities:index_activities')

    def post(self, request, *args, **kwargs):
        activity = get_object_or_404(Activity, pk=self.kwargs['pk'])
        if self.request.user != activity.created_by:
            return HttpResponse(status=403)

        return super(DeleteActivityView, self).post(request)


class UpdateActivityInstanceView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        try:
            activity_pk = request.POST.get("activity_pk")
            complete = request.POST.get("complete")
            start_difficulty = request.POST.get("start_difficulty")
            activity_difficulty = request.POST.get("activity_difficulty")
        except KeyError:
            return HttpResponse(status=403)

        activity_instance = get_object_or_404(ActivityInstance, pk=activity_pk)
        if self.request.user != activity_instance.activity.created_by:
            return HttpResponse(status=403)

        if complete == "true":
            new_activity_state = True
        elif complete == "false":
            new_activity_state = False
        else:
            return HttpResponse(status=403)
        old_activity_state = activity_instance.is_complete
        activity_instance.is_complete = new_activity_state
        activity_instance.start_difficulty = start_difficulty
        activity_instance.activity_difficulty = activity_difficulty
        activity_instance.save()

        if old_activity_state != new_activity_state:
            self.request.user.evaluate_level_progress(activity_instance)
            achievements = activity_instance.activity.achievements.all()
            for achievement in achievements:
                achievement.evaluate_achievement(activity_instance)

        return HttpResponse(status=200)


class ActivityStatisticsView(LoginRequiredMixin, TemplateView):
    template_name = "activity_statistics.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            date_format = "%A"
            current_activity = get_object_or_404(Activity, pk=self.kwargs['pk'], created_by=self.request.user)
            day_dict, start_activity_difficulty_dict, activity_difficulty_dict = get_activity_statistics(self.request.user, date_format, activity=current_activity)
            context['current_activity'] = current_activity
            context['day_dict'] = day_dict
            context['start_activity_difficulty_dict'] = start_activity_difficulty_dict
            context['activity_difficulty_dict'] = activity_difficulty_dict
            return context
        except KeyError:
            return context
        except Activity.DoesNotExist:
            return context

bi_bap/activities/templates/activity_statistics.html
{% extends 'base.html' %}
{% load static %}
{% load custom_template_tags %}

{% block include %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock %}
{% block content %}
<div class="row mb-3 d-flex justify-content-center">
    <div class="align-middle text-center display-4 p-2">{{current_activity}}</div>
</div>
<div class="row">
    {% if day_dict %}
    <div class="col-12 mb-3">
        <canvas id="day_dict_chart" width="100" height="60"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_start_difficulty_dict_chart" width="200" height="200"></canvas>
    </div>
    <div class="col-lg-6 col-12 mb-3">
        <canvas id="activity_difficulty_dict_chart" width="200" height="200"></canvas>
    </div>
    {% else %}
    <span class="display-4 text-center">No statistics to show</span>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
{% if day_dict %}
    <script>
    day_dict_labels = [];
    day_dict_values = [];
    {% for key, value in day_dict.items %}
        day_dict_labels.push("{{key}}");
        day_dict_values.push({{value.calculate_percentage}});
    {% endfor %}

    start_activity_difficulty_dict_labels = [];
    start_activity_difficulty_dict_values = [];
    {% for key, value in start_activity_difficulty_dict.items %}
        start_activity_difficulty_dict_labels.push("{{key}}");
        start_activity_difficulty_dict_values.push({{value.calculate_average}});
    {% endfor %}

    activity_difficulty_dict_labels = [];
    activity_difficulty_dict_values = [];
    {% for key, value in activity_difficulty_dict.items %}
        activity_difficulty_dict_labels.push("{{key}}");
        activity_difficulty_dict_values.push({{value.calculate_average}});
    {% endfor %}

    </script>
    <script src="{% static 'js/activity_statistics.js' %}"></script>
{% endif %}
{% endblock %}

bi_bap/activities/templates/create_activity.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {{ form.media }}
    {% csrf_token %}
    <div class="pe-3 ps-3">
        <h1 class="display-2 p-2">New activity</h1>
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}
               <ul class="list-group list-group-flush">
            <li class="list-group-item background-lightest">
                <div class="row">
                    <div class="form-group col-12 ">
                        <label class="h6">{{form.name.label}}</label>
                        {{form.name}}
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-6">
                        <label class="h6">{{form.start_date.label}}</label>
                        {{form.start_date}}
                    </div>
                    <div class="form-group col-6">
                        <label class="h6">{{form.end_date.label}}</label>
                        {{form.end_date}}
                    </div>
                </div>
            </li>
            <li class="list-group-item background-lightest">
                <div class="h5 mt-1 mb-3"> Choose weekdays for your activity: </div>
                <div class="row mb-2">
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.monday}}
                        <label class="h6">{{form.monday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.tuesday}}
                        <label class="h6">{{form.tuesday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.wednesday}}
                        <label class="h6">{{form.wednesday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.thursday}}
                        <label class="h6">{{form.thursday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.friday}}
                        <label class="h6">{{form.friday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.saturday}}
                        <label class="h6">{{form.saturday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.sunday}}
                        <label class="h6">{{form.sunday.label}}</label>
                    </div>
                </div>
                <div class="row justify-content-center mt-4">
                    <button class="custom-btn btn w-25">Submit</button>
                </div>
                        </li>


        </ul>

    </div>
</form>
{% endblock %}

bi_bap/activities/templates/index_activities.html
{% extends 'base.html' %}
{% load static %}
{% block include %}
    <link rel="stylesheet" href="{% static 'css/activities/index_activities.css' %}">
{% endblock %}

{% block content %}
<div class="row mb-2 p-2">
    <div class="d-flex justify-content-between align-items-center"><span class="display-4 text-color-darkest">Activities:</span>
        <a class="btn custom-btn" href="{% url 'activities:create_activity'%}"><i class="fas fa-plus me-1"></i> New</a>
    </div>
</div>
<div class="row ml-3 mr-3">
    <div id="activity-scrollbar" class="table-responsive">
        <table class="table table-bordered text-nowrap" cellspacing=0>
            <thead class="table-bordered background-darkest text-white">
            <tr>
                <th scope="col">
                        <span>
                            Activity
                        </span>
                </th>
                <th scope="col">
                        <span>
                            Interval
                        </span>
                </th>
                <th scope="col">
                        <span>
                            Weekdays
                        </span>
                </th>
                <th scope="col">

                </th>
            </tr>
            </thead>
            <tbody>
            {% for activity in current_activities %}

            <tr>
                <td class="align-middle">
                    <span>{{activity}}</span>
                </td>
                <td class="align-middle">
                    <span>{{activity.get_interval}}</span>
                </td>
                <td class="align-middle h-100">
                    <div class="d-flex justify-content-start">
                    <div class="day-container d-flex flex-column align-items-center m-1">
                        <b>Mon</b>
                        {% if activity.monday %}
                        <i class="fas fa-check text-success"></i>
                        {% else %}
                        <i class="fas fa-times text-danger"></i>
                        {% endif %}
                    </div>
                    <div class="day-container d-flex flex-column align-items-center m-1">
                        <b>Tue</b>
                        {% if activity.tuesday %}
                        <i class="fas fa-check text-success"></i>
                        {% else %}
                        <i class="fas fa-times text-danger"></i>
                        {% endif %}
                    </div>
                    <div class="day-container d-flex flex-column align-items-center m-1">
                        <b>Wed</b>
                        {% if activity.wednesday %}
                        <i class="fas fa-check text-success"></i>
                        {% else %}
                        <i class="fas fa-times text-danger"></i>
                        {% endif %}
                    </div>
                    <div class="day-container d-flex flex-column align-items-center m-1">
                        <b>Thu</b>
                        {% if activity.thursday %}
                        <i class="fas fa-check text-success"></i>
                        {% else %}
                        <i class="fas fa-times text-danger"></i>
                        {% endif %}
                    </div>
                    <div class="day-container d-flex flex-column align-items-center m-1">
                        <b>Fri</b>
                        {% if activity.friday %}
                        <i class="fas fa-check text-success"></i>
                        {% else %}
                        <i class="fas fa-times text-danger"></i>
                        {% endif %}
                    </div>
                    <div class="day-container d-flex flex-column align-items-center m-1">
                        <b>Sat</b>
                        {% if activity.saturday %}
                        <i class="fas fa-check text-success"></i>
                        {% else %}
                        <i class="fas fa-times text-danger"></i>
                        {% endif %}
                    </div>
                    <div class="day-container d-flex flex-column align-items-center m-1">
                        <b>Sun</b>
                        {% if activity.sunday %}
                        <i class="fas fa-check text-success"></i>
                        {% else %}
                        <i class="fas fa-times text-danger"></i>
                        {% endif %}
                    </div>
                    </div>
                </td>
                <td class="align-middle text-center">
                    <div class="activity-actions d-flex flex-row justify-content-center">
                            <a class="btn custom-btn m-1" href="{% url 'activities:activity_statistics' pk=activity.pk %}">
                                <i class="fas fa-chart-bar"></i>
                            </a>
                            <a class="btn custom-btn m-1" href="{% url 'activities:update_activity' pk=activity.pk %}"
                               title="Update">
                                <i class="fas fa-edit"></i>
                            </a>
                    </div>
                </td>

            </tr>
            {% empty %}
            <tr>
                <td colspan="4">No activities found.</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

bi_bap/activities/templates/update_activity.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form id="activity_edit" action="" method="post">
    {{ form.media }}
    {% csrf_token %}
    <div class="pe-3 ps-3">
        <div class="header d-flex justify-content-between align-items-center">
            <h1 class="display-4 p-2">{{object.name}}</h1>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalForm">
              Delete
            </button>
        </div>
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}
        <ul class="list-group list-group-flush">
            <li class="list-group-item background-lightest">
                <div class="row mb-2">
                    <div class="form-group col-sm-6 col-12">
                        <label class="h6">{{form.name.label}}</label>
                        {{form.name}}
                    </div>
                    <div class="form-group col-sm-6 col-12">
                        <label class="h6">Choose an action</label>
                        {{form.action}}
                    </div>
                </div>

                <div class="row mb-2">
                    <div class="form-group col-6">
                        <label class="h6">{{form.start_date.label}}</label>
                        {{form.start_date}}
                    </div>
                    <div class="form-group col-6">
                        <label class="h6">{{form.end_date.label}}</label>
                        {{form.end_date}}
                    </div>
                </div>
            </li>
            <li class="list-group-item background-lightest">
                <div class="h5 mt-1 mb-3"> Choose weekdays for your activity: </div>
                <div class="row mb-2">
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.monday}}
                        <label class="h6">{{form.monday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.tuesday}}
                        <label class="h6">{{form.tuesday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.wednesday}}
                        <label class="h6">{{form.wednesday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.thursday}}
                        <label class="h6">{{form.thursday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.friday}}
                        <label class="h6">{{form.friday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.saturday}}
                        <label class="h6">{{form.saturday.label}}</label>
                    </div>
                    <div class="form-check form-switch col-md-12 ms-3">
                        {{form.sunday}}
                        <label class="h6">{{form.sunday.label}}</label>
                    </div>
                </div>
                        </li>

            <li class="list-group-item background-lightest">
                <div class="row mb-4 mt-2">

                </div>
                <div class="row justify-content-center">
                    <button class="custom-btn btn w-25">Submit</button>
                </div>
            </li>


        </ul>

    </div>
</form>

<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header background-darkest">
        <h5 class="modal-title text-white" id="exampleModalLongTitle">Delete activity "{{object.name}}"?</h5>
        <button type="button" class="close btn background-lightest" data-bs-dismiss="modal" aria-label="Close">
            <i class="fas fa-times"></i>
        </button>
      </div>
        <form action="{% url 'activities:delete_activity' pk=object.pk %}" method="post">
            {% csrf_token %}
          <div class="modal-body">
              <span class="display-6">Do you wish to delete this activity?</span>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-danger">Confirm</button>
          </div>
        </form>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/activity_edit.js' %}"></script>
{% endblock %}